apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
data:
  key: QVFCMFNydGRBRmd4QnhBQU1CS2FadTVpcENOZVZGMTl3czBmUUE9PQ==   # Replace with your admin key
type: kubernetes.io/rbd
