apiVersion: v1
kind: Pod
metadata:
  name: ready
  labels:
    name: ready
spec:
  containers:
  - name: simpleservice-web
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - name: web
      containerPort: 9876
      protocol: TCP
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health
        port: 9876
    readinessProbe:
      httpGet:
        path: /info
        port: 9876
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    env:
    - name: HEALTH_MIN
      value: "1"
    - name: HEALTH_MAX
      value: "2"

